//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceModel", Namespace="http://schemas.datacontract.org/2004/07/SampleProjectWCF")]
    [System.SerializableAttribute()]
    public partial class PerformanceModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AverageScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CommunicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ConsistencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InitiativeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LearningAbilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProblemSolvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProductivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PunctualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QualityOfWorkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaskCompletionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TeamworkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AverageScore {
            get {
                return this.AverageScoreField;
            }
            set {
                if ((this.AverageScoreField.Equals(value) != true)) {
                    this.AverageScoreField = value;
                    this.RaisePropertyChanged("AverageScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Communication {
            get {
                return this.CommunicationField;
            }
            set {
                if ((this.CommunicationField.Equals(value) != true)) {
                    this.CommunicationField = value;
                    this.RaisePropertyChanged("Communication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Consistency {
            get {
                return this.ConsistencyField;
            }
            set {
                if ((this.ConsistencyField.Equals(value) != true)) {
                    this.ConsistencyField = value;
                    this.RaisePropertyChanged("Consistency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Feedback {
            get {
                return this.FeedbackField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedbackField, value) != true)) {
                    this.FeedbackField = value;
                    this.RaisePropertyChanged("Feedback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Initiative {
            get {
                return this.InitiativeField;
            }
            set {
                if ((this.InitiativeField.Equals(value) != true)) {
                    this.InitiativeField = value;
                    this.RaisePropertyChanged("Initiative");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LearningAbility {
            get {
                return this.LearningAbilityField;
            }
            set {
                if ((this.LearningAbilityField.Equals(value) != true)) {
                    this.LearningAbilityField = value;
                    this.RaisePropertyChanged("LearningAbility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProblemSolving {
            get {
                return this.ProblemSolvingField;
            }
            set {
                if ((this.ProblemSolvingField.Equals(value) != true)) {
                    this.ProblemSolvingField = value;
                    this.RaisePropertyChanged("ProblemSolving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Productivity {
            get {
                return this.ProductivityField;
            }
            set {
                if ((this.ProductivityField.Equals(value) != true)) {
                    this.ProductivityField = value;
                    this.RaisePropertyChanged("Productivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Punctuality {
            get {
                return this.PunctualityField;
            }
            set {
                if ((this.PunctualityField.Equals(value) != true)) {
                    this.PunctualityField = value;
                    this.RaisePropertyChanged("Punctuality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QualityOfWork {
            get {
                return this.QualityOfWorkField;
            }
            set {
                if ((this.QualityOfWorkField.Equals(value) != true)) {
                    this.QualityOfWorkField = value;
                    this.RaisePropertyChanged("QualityOfWork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaskCompletion {
            get {
                return this.TaskCompletionField;
            }
            set {
                if ((this.TaskCompletionField.Equals(value) != true)) {
                    this.TaskCompletionField = value;
                    this.RaisePropertyChanged("TaskCompletion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Teamwork {
            get {
                return this.TeamworkField;
            }
            set {
                if ((this.TeamworkField.Equals(value) != true)) {
                    this.TeamworkField = value;
                    this.RaisePropertyChanged("Teamwork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RateEmployee", ReplyAction="http://tempuri.org/IService1/RateEmployeeResponse")]
        bool RateEmployee(SampleProject.UserService.PerformanceModel model, int managerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RateEmployee", ReplyAction="http://tempuri.org/IService1/RateEmployeeResponse")]
        System.Threading.Tasks.Task<bool> RateEmployeeAsync(SampleProject.UserService.PerformanceModel model, int managerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPerformanceHistory", ReplyAction="http://tempuri.org/IService1/GetPerformanceHistoryResponse")]
        SampleProject.UserService.PerformanceModel[] GetPerformanceHistory(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPerformanceHistory", ReplyAction="http://tempuri.org/IService1/GetPerformanceHistoryResponse")]
        System.Threading.Tasks.Task<SampleProject.UserService.PerformanceModel[]> GetPerformanceHistoryAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SampleProject.UserService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SampleProject.UserService.IService1>, SampleProject.UserService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RateEmployee(SampleProject.UserService.PerformanceModel model, int managerId) {
            return base.Channel.RateEmployee(model, managerId);
        }
        
        public System.Threading.Tasks.Task<bool> RateEmployeeAsync(SampleProject.UserService.PerformanceModel model, int managerId) {
            return base.Channel.RateEmployeeAsync(model, managerId);
        }
        
        public SampleProject.UserService.PerformanceModel[] GetPerformanceHistory(int userId) {
            return base.Channel.GetPerformanceHistory(userId);
        }
        
        public System.Threading.Tasks.Task<SampleProject.UserService.PerformanceModel[]> GetPerformanceHistoryAsync(int userId) {
            return base.Channel.GetPerformanceHistoryAsync(userId);
        }
    }
}
